<?php

namespace ContainerH1fKrSZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodo2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WYf3Hmo.App\Entity\Todo' shared service.
     *
     * @return \App\Entity\Todo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WYf3Hmo": it references class "App\\Entity\\Todo" but no such service exists.');
    }
}
