<?php

namespace Container7fY5407;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WYf3HmoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WYf3Hmo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WYf3Hmo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'todo' => ['privates', '.errored..service_locator.WYf3Hmo.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.WYf3Hmo": it references class "App\\Entity\\Todo" but no such service exists.'],
            'todoRepository' => ['privates', 'App\\Repository\\TodoRepository', 'getTodoRepositoryService', true],
        ], [
            'todo' => 'App\\Entity\\Todo',
            'todoRepository' => 'App\\Repository\\TodoRepository',
        ]);
    }
}
