<?php

namespace Container7fY5407;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHxLxYPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IHxLxYP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IHxLxYP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'todo' => ['privates', '.errored..service_locator.IHxLxYP.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.IHxLxYP": it references class "App\\Entity\\Todo" but no such service exists.'],
        ], [
            'todo' => 'App\\Entity\\Todo',
        ]);
    }
}
